using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace SquadBuilderNS
{
    public static class PreGeneratedAiSquadrons
    {
        public static readonly Dictionary<string, string> Squadrons = new Dictionary<string, string>()
        {
            { "BlueSquadron",       "{\"name\":\"Blue Squadron\",\"faction\":\"rebel\",\"points\":100,\"version\":\"0.3.0\",\"pilots\":[{\"name\":\"bluesquadronnovice\",\"points\":25,\"ship\":\"t70xwing\",\"upgrades\":{\"mod\":[\"integratedastromech\"],\"amd\":[\"r5astromech\"]},\"vendor\":{\"Sandrem.FlyCasual\":{\"skin\":\"Blue\"}}},{\"name\":\"bluesquadronnovice\",\"points\":25,\"ship\":\"t70xwing\",\"upgrades\":{\"mod\":[\"integratedastromech\"],\"amd\":[\"r5astromech\"]},\"vendor\":{\"Sandrem.FlyCasual\":{\"skin\":\"Blue\"}}},{\"name\":\"bluesquadronnovice\",\"points\":25,\"ship\":\"t70xwing\",\"upgrades\":{\"mod\":[\"integratedastromech\"],\"amd\":[\"r5astromech\"]},\"vendor\":{\"Sandrem.FlyCasual\":{\"skin\":\"Blue\"}}},{\"name\":\"bluesquadronnovice\",\"points\":25,\"ship\":\"t70xwing\",\"upgrades\":{\"mod\":[\"integratedastromech\"],\"amd\":[\"r5astromech\"]},\"vendor\":{\"Sandrem.FlyCasual\":{\"skin\":\"Blue\"}}}],\"description\":\"Blue Squadron Novice + Integrated Astromech + R5 Astromech\nBlue Squadron Novice + Integrated Astromech + R5 Astromech\nBlue Squadron Novice + Integrated Astromech + R5 Astromech\nBlue Squadron Novice + Integrated Astromech + R5 Astromech\"}" },
            { "ScurrgAlpha",        "{\"name\":\"Scurrg Alpha\",\"faction\":\"scum\",\"points\":99,\"version\":\"0.3.0\",\"pilots\":[{\"name\":\"lokrevenant\",\"points\":33,\"ship\":\"scurrgh6bomber\",\"upgrades\":{\"mod\":[\"guidancechips\"],\"turret\":[\"autoblasterturret\"],\"missile\":[\"harpoonmissiles\"],\"ept\":[\"deadeye\"]},\"vendor\":{\"Sandrem.FlyCasual\":{\"skin\":\"Lok Revenant\"}}},{\"name\":\"lokrevenant\",\"points\":33,\"ship\":\"scurrgh6bomber\",\"upgrades\":{\"mod\":[\"guidancechips\"],\"turret\":[\"autoblasterturret\"],\"missile\":[\"harpoonmissiles\"],\"ept\":[\"deadeye\"]},\"vendor\":{\"Sandrem.FlyCasual\":{\"skin\":\"Lok Revenant\"}}},{\"name\":\"lokrevenant\",\"points\":33,\"ship\":\"scurrgh6bomber\",\"upgrades\":{\"mod\":[\"guidancechips\"],\"turret\":[\"autoblasterturret\"],\"missile\":[\"harpoonmissiles\"],\"ept\":[\"deadeye\"]},\"vendor\":{\"Sandrem.FlyCasual\":{\"skin\":\"Lok Revenant\"}}}],\"description\":\"Lok Revenant + Guidance Chips + Autoblaster Turret + Harpoon Missiles + Deadeye\nLok Revenant + Guidance Chips + Autoblaster Turret + Harpoon Missiles + Deadeye\nLok Revenant + Guidance Chips + Autoblaster Turret + Harpoon Missiles + Deadeye\"}}" },
            { "StormSquadron",      "{\"name\":\"Storm Squadron\",\"faction\":\"imperial\",\"points\":96,\"version\":\"0.3.0\",\"pilots\":[{\"name\":\"stormsquadronpilot\",\"points\":24,\"ship\":\"tieadv\",\"upgrades\":{\"title\":[\"tiex1\"],\"system\":[\"advtargetingcomputer\"]},\"vendor\":{\"Sandrem.FlyCasual\":{\"skin\":\"Gray\"}}},{\"name\":\"stormsquadronpilot\",\"points\":24,\"ship\":\"tieadv\",\"upgrades\":{\"title\":[\"tiex1\"],\"system\":[\"advtargetingcomputer\"]},\"vendor\":{\"Sandrem.FlyCasual\":{\"skin\":\"Gray\"}}},{\"name\":\"stormsquadronpilot\",\"points\":24,\"ship\":\"tieadv\",\"upgrades\":{\"title\":[\"tiex1\"],\"system\":[\"advtargetingcomputer\"]},\"vendor\":{\"Sandrem.FlyCasual\":{\"skin\":\"Gray\"}}},{\"name\":\"stormsquadronpilot\",\"points\":24,\"ship\":\"tieadv\",\"upgrades\":{\"title\":[\"tiex1\"],\"system\":[\"advtargetingcomputer\"]},\"vendor\":{\"Sandrem.FlyCasual\":{\"skin\":\"Gray\"}}}],\"description\":\"Storm Squadron Pilot + TIE/x1 + Adv. Targeting Computer\nStorm Squadron Pilot + TIE/x1 + Adv. Targeting Computer\nStorm Squadron Pilot + TIE/x1 + Adv. Targeting Computer\nStorm Squadron Pilot + TIE/x1 + Adv. Targeting Computer\"}" },
            { "TacticalWookiees",   "{\"name\":\"Tactical Wookiees\",\"faction\":\"rebel\",\"points\":98,\"version\":\"0.3.0\",\"pilots\":[{\"name\":\"wookieeliberator\",\"points\":32,\"ship\":\"auzituckgunship\",\"upgrades\":{\"crew\":[\"tactician\"],\"ept\":[\"expertise\"]},\"vendor\":{\"Sandrem.FlyCasual\":{\"skin\":\"Kashyyyk Defender\"}}},{\"name\":\"lowhhrick\",\"points\":34,\"ship\":\"auzituckgunship\",\"upgrades\":{\"crew\":[\"tactician\"],\"ept\":[\"expertise\"]},\"vendor\":{\"Sandrem.FlyCasual\":{\"skin\":\"Lowhhrick\"}}},{\"name\":\"wookieeliberator\",\"points\":32,\"ship\":\"auzituckgunship\",\"upgrades\":{\"crew\":[\"tactician\"],\"ept\":[\"expertise\"]},\"vendor\":{\"Sandrem.FlyCasual\":{\"skin\":\"Kashyyyk Defender\"}}}],\"description\":\"Wookiee Liberator + Tactician + Expertise\nLowhhrick + Tactician + Expertise\nWookiee Liberator + Tactician + Expertise\"}"},
            { "ThugLife",           "{\"name\":\"Thug Life\",\"faction\":\"scum\",\"points\":100,\"version\":\"0.3.0\",\"pilots\":[{\"name\":\"syndicatethug\",\"points\":25,\"ship\":\"ywing\",\"upgrades\":{\"turret\":[\"twinlaserturret\"],\"samd\":[\"unhingedastromech\"]},\"vendor\":{\"Sandrem.FlyCasual\":{\"skin\":\"Brown\"}}},{\"name\":\"syndicatethug\",\"points\":25,\"ship\":\"ywing\",\"upgrades\":{\"turret\":[\"twinlaserturret\"],\"samd\":[\"unhingedastromech\"]},\"vendor\":{\"Sandrem.FlyCasual\":{\"skin\":\"Brown\"}}},{\"name\":\"syndicatethug\",\"points\":25,\"ship\":\"ywing\",\"upgrades\":{\"turret\":[\"twinlaserturret\"],\"samd\":[\"unhingedastromech\"]},\"vendor\":{\"Sandrem.FlyCasual\":{\"skin\":\"Brown\"}}},{\"name\":\"syndicatethug\",\"points\":25,\"ship\":\"ywing\",\"upgrades\":{\"turret\":[\"twinlaserturret\"],\"samd\":[\"unhingedastromech\"]},\"vendor\":{\"Sandrem.FlyCasual\":{\"skin\":\"Brown\"}}}],\"description\":\"Syndicate Thug + Twin Laser Turret + Unhinged Astromech\nSyndicate Thug + Twin Laser Turret + Unhinged Astromech\nSyndicate Thug + Twin Laser Turret + Unhinged Astromech\nSyndicate Thug + Twin Laser Turret + Unhinged Astromech\"}" },
            { "TripleDefenders",    "{\"name\":\"Triple Defenders\",\"faction\":\"imperial\",\"points\":99,\"version\":\"0.3.0\",\"pilots\":[{\"name\":\"glaivesquadronpilot\",\"points\":33,\"ship\":\"tiedefender\",\"upgrades\":{\"title\":[\"tiex7\"],\"ept\":[\"veteraninstincts\"]},\"vendor\":{\"Sandrem.FlyCasual\":{\"skin\":\"Crimson\"}}},{\"name\":\"glaivesquadronpilot\",\"points\":33,\"ship\":\"tiedefender\",\"upgrades\":{\"title\":[\"tiex7\"],\"ept\":[\"veteraninstincts\"]},\"vendor\":{\"Sandrem.FlyCasual\":{\"skin\":\"Crimson\"}}},{\"name\":\"glaivesquadronpilot\",\"points\":33,\"ship\":\"tiedefender\",\"upgrades\":{\"title\":[\"tiex7\"],\"ept\":[\"veteraninstincts\"]},\"vendor\":{\"Sandrem.FlyCasual\":{\"skin\":\"Crimson\"}}}],\"description\":\"Glaive Squadron Pilot + TIE/x7 + Veteran Instincts\nGlaive Squadron Pilot + TIE/x7 + Veteran Instincts\nGlaive Squadron Pilot + TIE/x7 + Veteran Instincts\"}" }
        };
    }
}
