namespace ExtraOptions
{
    namespace ExtraOptionsList
    {
        public class NoDefaultAiSquadronsExtraOption : ExtraOption
        {
            public NoDefaultAiSquadronsExtraOption()
            {
                Name = "No Default Squadrons for the AI";
                Description =
                    "By default, the app searches for squadrons for the AI in folders \"Default\" (were generated by developers) and \"Custom\" (place for player-generated squadrons). " +
                    "If this option is ON, the app searches only in folder \"Custom\"\n" +
                    "(Folders path (Windows): %userprofile%\\AppData\\LocalLow\\Sandrem\\Fly Casual\\Second Edition\\AiSquadrons)\n" +
                    "(Folders path (MacOS): ~/Library/Application Support/unity.Sandrem.X-Wing TMG Simulator/Second Edition/AiSquadrons)";
            }

            protected override void Activate()
            {
                DebugManager.NoDefaultAiSquads = true;
            }

            protected override void Deactivate()
            {
                DebugManager.NoDefaultAiSquads = false;
            }
        }
    }
}
